# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/re0ah/bytecode-interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/re0ah/bytecode-interpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/re0ah/bytecode-interpreter/CMakeFiles /home/re0ah/bytecode-interpreter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/re0ah/bytecode-interpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interpriter

# Build rule for target.
interpriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpriter
.PHONY : interpriter

# fast build rule for target.
interpriter/fast:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/build
.PHONY : interpriter/fast

cpu.o: cpu.c.o

.PHONY : cpu.o

# target to build an object file
cpu.c.o:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/cpu.c.o
.PHONY : cpu.c.o

cpu.i: cpu.c.i

.PHONY : cpu.i

# target to preprocess a source file
cpu.c.i:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/cpu.c.i
.PHONY : cpu.c.i

cpu.s: cpu.c.s

.PHONY : cpu.s

# target to generate assembly for a file
cpu.c.s:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/cpu.c.s
.PHONY : cpu.c.s

instructions.o: instructions.c.o

.PHONY : instructions.o

# target to build an object file
instructions.c.o:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/instructions.c.o
.PHONY : instructions.c.o

instructions.i: instructions.c.i

.PHONY : instructions.i

# target to preprocess a source file
instructions.c.i:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/instructions.c.i
.PHONY : instructions.c.i

instructions.s: instructions.c.s

.PHONY : instructions.s

# target to generate assembly for a file
instructions.c.s:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/instructions.c.s
.PHONY : instructions.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/interpriter.dir/build.make CMakeFiles/interpriter.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... interpriter"
	@echo "... edit_cache"
	@echo "... cpu.o"
	@echo "... cpu.i"
	@echo "... cpu.s"
	@echo "... instructions.o"
	@echo "... instructions.i"
	@echo "... instructions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

